[2025-08-22T04:01:52.508+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-22T04:01:52.534+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_stg.load_special_data manual__2025-08-22T04:01:37+00:00 [queued]>
[2025-08-22T04:01:52.549+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_stg.load_special_data manual__2025-08-22T04:01:37+00:00 [queued]>
[2025-08-22T04:01:52.549+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-08-22T04:01:52.571+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): load_special_data> on 2025-08-22 04:01:37+00:00
[2025-08-22T04:01:52.593+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=768) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-22T04:01:52.597+0000] {standard_task_runner.py:72} INFO - Started process 776 to run task
[2025-08-22T04:01:52.597+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_stg', 'load_special_data', 'manual__2025-08-22T04:01:37+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_stg.py', '--cfg-path', '/tmp/tmpfvpmy_61']
[2025-08-22T04:01:52.605+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask load_special_data
[2025-08-22T04:01:53.171+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline_stg.load_special_data manual__2025-08-22T04:01:37+00:00 [running]> on host 21c40e4c1785
[2025-08-22T04:01:53.333+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline_stg' AIRFLOW_CTX_TASK_ID='load_special_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-22T04:01:37+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-22T04:01:37+00:00'
[2025-08-22T04:01:53.334+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-08-22T04:01:53.385+0000] {logging_mixin.py:190} INFO - Error during special data creation and loading: No module named 'create_special_ship_data'
[2025-08-22T04:01:53.386+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline_stg.py", line 92, in create_and_load_special_data
    from create_special_ship_data import create_submarine_data, create_model_master_data, generate_time_series_data
ModuleNotFoundError: No module named 'create_special_ship_data'
[2025-08-22T04:01:53.409+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_pipeline_stg, task_id=load_special_data, run_id=manual__2025-08-22T04:01:37+00:00, execution_date=20250822T040137, start_date=20250822T040152, end_date=20250822T040153
[2025-08-22T04:01:53.439+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-08-22T04:01:53.440+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task load_special_data (No module named 'create_special_ship_data'; 776)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline_stg.py", line 92, in create_and_load_special_data
    from create_special_ship_data import create_submarine_data, create_model_master_data, generate_time_series_data
ModuleNotFoundError: No module named 'create_special_ship_data'
[2025-08-22T04:01:53.507+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-08-22T04:01:53.546+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
