[2025-08-22T05:01:14.209+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-22T05:01:14.253+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_bi.create_map_data manual__2025-08-22T05:01:07+00:00 [queued]>
[2025-08-22T05:01:14.272+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_bi.create_map_data manual__2025-08-22T05:01:07+00:00 [queued]>
[2025-08-22T05:01:14.273+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-08-22T05:01:14.307+0000] {taskinstance.py:2879} INFO - Executing <Task(PostgresOperator): create_map_data> on 2025-08-22 05:01:07+00:00
[2025-08-22T05:01:14.331+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1569) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-22T05:01:14.335+0000] {standard_task_runner.py:72} INFO - Started process 1572 to run task
[2025-08-22T05:01:14.343+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_bi', 'create_map_data', 'manual__2025-08-22T05:01:07+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_bi.py', '--cfg-path', '/tmp/tmp0_7k_sxs']
[2025-08-22T05:01:14.364+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask create_map_data
[2025-08-22T05:01:14.518+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline_bi.create_map_data manual__2025-08-22T05:01:07+00:00 [running]> on host 21c40e4c1785
[2025-08-22T05:01:14.809+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline_bi' AIRFLOW_CTX_TASK_ID='create_map_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-22T05:01:07+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-22T05:01:07+00:00'
[2025-08-22T05:01:14.813+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-08-22T05:01:14.854+0000] {sql.py:282} INFO - Executing: 
        -- 지도 시각화에 필요한 상세 정보만 담는 테이블을 생성합니다.
        DROP TABLE IF EXISTS bi.shipbuilding_map_data;

        CREATE TABLE bi.shipbuilding_map_data AS
        SELECT
            project_id,
            product_type,
            business_unit,
            country,
            revenue,
            latitude,
            longitude
        FROM mart.shipbuilding_orders_clean
        WHERE latitude IS NOT NULL AND longitude IS NOT NULL;
        
[2025-08-22T05:01:14.875+0000] {base.py:84} INFO - Retrieving connection 'datalake_1'
[2025-08-22T05:01:14.891+0000] {base.py:84} INFO - Retrieving connection 'datalake_1'
[2025-08-22T05:01:14.942+0000] {sql.py:509} INFO - Running statement: 
        -- 지도 시각화에 필요한 상세 정보만 담는 테이블을 생성합니다.
        DROP TABLE IF EXISTS bi.shipbuilding_map_data;

        CREATE TABLE bi.shipbuilding_map_data AS
        SELECT
            project_id,
            product_type,
            business_unit,
            country,
            revenue,
            latitude,
            longitude
        FROM mart.shipbuilding_orders_clean
        WHERE latitude IS NOT NULL AND longitude IS NOT NULL;
        , parameters: None
[2025-08-22T05:01:14.946+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "mart.shipbuilding_orders_clean" does not exist
LINE 14:         FROM mart.shipbuilding_orders_clean
                      ^

[2025-08-22T05:01:14.975+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_pipeline_bi, task_id=create_map_data, run_id=manual__2025-08-22T05:01:07+00:00, execution_date=20250822T050107, start_date=20250822T050114, end_date=20250822T050114
[2025-08-22T05:01:14.996+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-08-22T05:01:15.002+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 19 for task create_map_data (relation "mart.shipbuilding_orders_clean" does not exist
LINE 14:         FROM mart.shipbuilding_orders_clean
                      ^
; 1572)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "mart.shipbuilding_orders_clean" does not exist
LINE 14:         FROM mart.shipbuilding_orders_clean
                      ^

[2025-08-22T05:01:15.039+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-08-22T05:01:15.069+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-08-22T05:01:15.100+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-22T05:01:15.107+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
